"""Tutor-facing assigned-student APIs."""

DEFAULT_PAGE_LIMIT = 10
MAX_PAGE_LIMIT = 1000
PAGE_SIZE_OPTIONS = [10, 20, 30, 40, 50, 100, 200, 500]

RISK_NOT_STARTED = "Not Started"
RISK_LOW = "Low"
RISK_MEDIUM = "Medium"
RISK_HIGH = "High"
RISK_LEVELS = [RISK_NOT_STARTED, RISK_LOW, RISK_MEDIUM, RISK_HIGH]
