"""Generate chapter question banks. Run: python suneel_chapter_qa/gen_banks.py"""
from __future__ import annotations

import json
from pathlib import Path

BANKS = Path(__file__).resolve().parent / "banks"


def Q(qid, query, label, expect, forbidden=None, want_images=False, want_math=False, want_science=False):
    return {
        "id": qid,
        "query": query,
        "label": label,
        "expect_keywords": expect,
        "forbidden": forbidden or [],
        "want_images": want_images,
        "want_math": want_math,
        "want_science": want_science,
    }


def chapter(slug, subject, chapter_id, chapter_name, questions):
    assert len(questions) == 20, slug
    labels = [q["label"] for q in questions]
    assert sum(1 for x in labels if x == "typo") >= 2, (slug, labels)
    assert sum(1 for x in labels if x == "wrong") >= 2, (slug, labels)
    return {
        "slug": slug,
        "subject": subject,
        "chapter_id": str(chapter_id),
        "chapter": chapter_name,
        "board": "CBSE",
        "class_level": "CLASS_8",
        "questions": questions,
    }


CHAPTERS = [
    chapter("english_unit1", "English", 26, "Unit 1 - Wit and Wisdom", [
        Q("E1-01", "hey what is this unit Wit and Wisdom even about?", "normal", ["wit", "wisdom"]),
        Q("E1-02", "who is tenali or the witty person in this unit?", "normal", ["tenali", "rama", "wit"]),
        Q("E1-03", "what does wit mean here in simple words?", "normal", ["wit", "clever"]),
        Q("E1-04", "can you tell the main story briefly?", "normal", ["king", "queen", "story"]),
        Q("E1-05", "why did the king get angry at the queen?", "normal", ["king", "queen"]),
        Q("E1-06", "how did clever words fix the problem?", "normal", ["wit", "clever"]),
        Q("E1-07", "is there a poem or tricky writing in this chapter?", "normal", ["poem", "king", "wit"]),
        Q("E1-08", "what should i learn from this unit for life?", "normal", ["wit", "wisdom", "learn"]),
        Q("E1-09", "quiz me with one easy question on wit", "normal", ["wit", "question", "quiz", "?"]),
        Q("E1-10", "show me any picture or figure from this unit if there is one", "diagram", ["figure", "picture", "image", "illustration", "shown"], want_images=True),
        Q("E1-11", "what is wisdom different from wit?", "normal", ["wisdom", "wit"]),
        Q("E1-12", "can you give one funny moment from the chapter?", "normal", ["laugh", "funny", "wit", "yawn"]),
        Q("E1-13", "why is listening important in the story?", "normal", ["listen", "king", "queen", "wit"]),
        Q("E1-14", "explain the misunderstanding in simpler words", "normal", ["misunderstand", "king", "queen"]),
        Q("E1-15", "whats the theeem of wit and wisdum?", "typo", ["theme", "wit", "wisdom"]),
        Q("E1-16", "who was tenali ramakrisna again?", "typo", ["tenali", "rama", "wit"]),
        Q("E1-17", "who invented photosynthesis in Wit and Wisdom?", "wrong", ["wit", "wisdom", "chapter", "not"], ["photosynthesis"]),
        Q("E1-18", "did this unit teach gravity formulas?", "wrong", ["wit", "wisdom", "english", "not"], ["gravity", "formula"]),
        Q("E1-19", "i still dont get why the king stopped talking — explain again", "normal", ["king", "queen"]),
        Q("E1-20", "ok summarize the whole unit in 4 short bullets", "normal", ["wit", "wisdom"]),
    ]),
    chapter("english_unit2", "English", 27, "Unit 2 - Values and Dispositions", [
        Q("E2-01", "what values are they talking about in this chapter?", "normal", ["value"]),
        Q("E2-02", "what does disposition mean here?", "normal", ["disposition", "attitude", "value"]),
        Q("E2-03", "why do values matter for students like me?", "normal", ["value"]),
        Q("E2-04", "give me one example of a good value from the unit", "normal", ["value"]),
        Q("E2-05", "is honesty or kindness mentioned?", "normal", ["honest", "kind", "value", "respect"]),
        Q("E2-06", "how can i practice these values at school?", "normal", ["value", "school"]),
        Q("E2-07", "quiz me on one value from the chapter", "normal", ["value", "?", "quiz"]),
        Q("E2-08", "show a picture from this unit if the book has one", "diagram", ["figure", "picture", "image", "shown"], want_images=True),
        Q("E2-09", "what happens if we ignore good values?", "normal", ["value"]),
        Q("E2-10", "any story or character that shows good disposition?", "normal", ["disposition", "value", "story"]),
        Q("E2-11", "explain this unit like im in class 6", "normal", ["value"]),
        Q("E2-12", "what is the main message of Values and Dispositions?", "normal", ["value", "disposition"]),
        Q("E2-13", "how are values different from rules?", "normal", ["value", "rule"]),
        Q("E2-14", "can valus change how we treet frends?", "typo", ["value", "friend"]),
        Q("E2-15", "give two short points for my notebook", "normal", ["value"]),
        Q("E2-16", "what are valus and dispotisions about?", "typo", ["value", "disposition"]),
        Q("E2-17", "does this chapter teach quadratic equations?", "wrong", ["value", "english", "not"], ["quadratic"]),
        Q("E2-18", "who discovered bacteria in Values and Dispositions?", "wrong", ["value", "chapter", "not"], ["bacteria"]),
        Q("E2-19", "why is respect a disposition sometimes?", "normal", ["respect", "disposition", "value"]),
        Q("E2-20", "wrap up the unit in one short paragraph", "normal", ["value"]),
    ]),
    chapter("english_unit3", "English", 28, "Unit 3 - Mystery and Magic", [
        Q("E3-01", "is Mystery and Magic a story unit? what happens in it?", "normal", ["mystery", "magic"]),
        Q("E3-02", "what is mysterious in this chapter?", "normal", ["mystery"]),
        Q("E3-03", "is there real magic or just tricks/stories?", "normal", ["magic", "mystery"]),
        Q("E3-04", "who are the main characters?", "normal", ["character", "story"]),
        Q("E3-05", "can you summarize the plot in simple words?", "normal", ["story", "mystery"]),
        Q("E3-06", "why do people love mystery stories?", "normal", ["mystery"]),
        Q("E3-07", "quiz me with one easy question on this unit", "normal", ["mystery", "magic", "?"]),
        Q("E3-08", "show any figure or illustration from mystery and magic", "diagram", ["figure", "picture", "image", "shown"], want_images=True),
        Q("E3-09", "what lesson should i take from this unit?", "normal", ["lesson", "mystery", "magic"]),
        Q("E3-10", "is there suspense? where?", "normal", ["suspense", "mystery"]),
        Q("E3-11", "explain one magical moment from the text", "normal", ["magic", "mystery"]),
        Q("E3-12", "how does the mystery get solved if it does?", "normal", ["mystery", "solve"]),
        Q("E3-13", "what new words related to mystery?", "normal", ["mystery", "word"]),
        Q("E3-14", "would you call this fantasy? why?", "normal", ["fantasy", "magic", "mystery"]),
        Q("E3-15", "give me 3 bulletts about mistery unit", "typo", ["mystery", "magic"]),
        Q("E3-16", "whats mistery and magik about lol", "typo", ["mystery", "magic"]),
        Q("E3-17", "did harry potter write this CBSE chapter?", "wrong", ["mystery", "magic", "chapter", "not"], ["harry potter"]),
        Q("E3-18", "is photosynthesis the theme of Mystery and Magic?", "wrong", ["mystery", "magic", "not"], ["photosynthesis"]),
        Q("E3-19", "i got confused — is magic real in the story world?", "normal", ["magic", "story"]),
        Q("E3-20", "end with a short recap please", "normal", ["mystery", "magic"]),
    ]),
    chapter("math_ch1_square_cube", "Mathematics", 38, "Chapter-1 : A SQUARE AND A CUBE", [
        Q("M1-01", "wait so what is a perfect square? like in simple words", "normal", ["square"], want_math=True),
        Q("M1-02", "what is a perfect cube then?", "normal", ["cube"], want_math=True),
        Q("M1-03", "can you show how cube numbers work with an example?", "interactive", ["cube"], want_math=True),
        Q("M1-04", "is 36 a perfect square? why?", "normal", ["36", "square", "6"], want_math=True),
        Q("M1-05", "what about 27 — square or cube?", "normal", ["27", "cube"], want_math=True),
        Q("M1-06", "how do i find square root of a perfect square?", "normal", ["square", "root"], want_math=True),
        Q("M1-07", "show a figure or pattern of squares from the book", "diagram", ["square", "figure", "pattern"], want_images=True, want_math=True),
        Q("M1-08", "why do we call it a square number?", "normal", ["square"], want_math=True),
        Q("M1-09", "quiz me: give one easy square question", "normal", ["square", "?"], want_math=True),
        Q("M1-10", "what is 8 cubed?", "normal", ["512", "cube", "8"], want_math=True),
        Q("M1-11", "difference between square and cube in one line", "normal", ["square", "cube"], want_math=True),
        Q("M1-12", "are negative numbers perfect squares in this chapter?", "normal", ["square", "negative", "not"], want_math=True),
        Q("M1-13", "list three perfect squares between 1 and 100", "normal", ["square"], want_math=True),
        Q("M1-14", "list three perfect cubes between 1 and 100", "normal", ["cube"], want_math=True),
        Q("M1-15", "how is area related to square numbers?", "normal", ["area", "square"], want_math=True),
        Q("M1-16", "what is the squre of 12?", "typo", ["144", "square", "12"], want_math=True),
        Q("M1-17", "is square root of 2 a perfect square in this chapter?", "wrong", ["perfect", "square", "not"], want_math=True),
        Q("M1-18", "did this chapter invent the steam engine?", "wrong", ["square", "cube", "math", "not"], ["steam"]),
        Q("M1-19", "explain with steps how to check if 81 is a perfect square", "interactive", ["81", "square", "9"], want_math=True),
        Q("M1-20", "what is the cube of fivve?", "typo", ["125", "cube", "5"], want_math=True),
    ]),
    chapter("math_ch2_power_play", "Mathematics", 39, "Chapter-2 : POWER PLAY", [
        Q("M2-01", "what does power play mean? is it about exponents?", "normal", ["power", "exponent"], want_math=True),
        Q("M2-02", "ok explain 2 to the power 5 slowly", "interactive", ["32", "power", "2"], want_math=True),
        Q("M2-03", "what is a base and an exponent?", "normal", ["base", "exponent", "power"], want_math=True),
        Q("M2-04", "why do we use powers instead of long multiplications?", "normal", ["power", "multiply"], want_math=True),
        Q("M2-05", "what is 10 to the power 3?", "normal", ["1000", "10", "power"], want_math=True),
        Q("M2-06", "any laws of exponents in this chapter?", "normal", ["exponent", "law", "power"], want_math=True),
        Q("M2-07", "show a diagram or table about powers if the book has one", "diagram", ["power", "figure", "table"], want_images=True, want_math=True),
        Q("M2-08", "quiz me on powers with one easy question", "normal", ["power", "?"], want_math=True),
        Q("M2-09", "what happens when exponent is 0?", "normal", ["power", "zero", "1", "exponent"], want_math=True),
        Q("M2-10", "how do i multiply same bases with powers?", "normal", ["power", "multiply", "add"], want_math=True),
        Q("M2-11", "explain 3^4 with expanded form", "interactive", ["81", "3", "power"], want_math=True),
        Q("M2-12", "is 2^3 same as 3^2?", "normal", ["8", "9", "not", "power"], want_math=True),
        Q("M2-13", "real life use of powers?", "normal", ["power", "life", "example"], want_math=True),
        Q("M2-14", "big numbers with powers of 10?", "normal", ["power", "10"], want_math=True),
        Q("M2-15", "give two practice problems from this idea", "normal", ["power"], want_math=True),
        Q("M2-16", "what is 5 too the powr of 3?", "typo", ["125", "5", "power"], want_math=True),
        Q("M2-17", "is power play about electricity in social studies?", "wrong", ["power", "exponent", "math", "not"], ["electricity"]),
        Q("M2-18", "who were the mughals in power play math chapter?", "wrong", ["power", "math", "not"], ["mughal"]),
        Q("M2-19", "i keep forgetting — say again what exponent means", "normal", ["exponent", "power"], want_math=True),
        Q("M2-20", "explain 2^4 agian slowly pls", "typo", ["16", "power", "2"], want_math=True),
    ]),
    chapter("science_ch1_investigative", "Science", 35, "Chapter 1 - Exploring the Investigative World of Science", [
        Q("S1-01", "what is this chapter exploring the investigative world of science about?", "normal", ["science", "investigat"], want_science=True),
        Q("S1-02", "why do scientists investigate things?", "normal", ["investigat", "science"], want_science=True),
        Q("S1-03", "what is observation in science?", "normal", ["observation", "science"], want_science=True),
        Q("S1-04", "what is a hypothesis in simple words?", "normal", ["hypothesis"], want_science=True),
        Q("S1-05", "how does an experiment help us learn?", "interactive", ["experiment", "science"], want_science=True),
        Q("S1-06", "can you show a diagram or figure from this science chapter?", "diagram", ["figure", "diagram", "image"], want_images=True, want_science=True),
        Q("S1-07", "what skills do young scientists need?", "normal", ["skill", "science", "curious"], want_science=True),
        Q("S1-08", "quiz me one question on scientific investigation", "normal", ["science", "?", "investigat"], want_science=True),
        Q("S1-09", "what is the difference between guessing and investigating?", "normal", ["investigat", "guess"], want_science=True),
        Q("S1-10", "give a real life example of investigation around me", "normal", ["investigat", "example"], want_science=True),
        Q("S1-11", "why ask questions in science?", "normal", ["question", "science"], want_science=True),
        Q("S1-12", "what is data or evidence in this chapter?", "normal", ["data", "evidence", "science"], want_science=True),
        Q("S1-13", "steps of investigating something — list them", "interactive", ["step", "observ", "experiment"], want_science=True),
        Q("S1-14", "how is curiosity useful?", "normal", ["curious", "science"], want_science=True),
        Q("S1-15", "what should i write as notes from this chapter?", "normal", ["science", "investigat"], want_science=True),
        Q("S1-16", "explain fotosyntesis from this chapter pls", "typo", ["chapter", "science", "not", "investigat"], want_science=True),
        Q("S1-17", "does this chapter say the earth is flat?", "wrong", ["science", "not", "investigat"], ["flat"]),
        Q("S1-18", "is health the only topic here?", "wrong", ["investigat", "science"], want_science=True),
        Q("S1-19", "i'm lost — restart with what investigasion means", "typo", ["investigat"], want_science=True),
        Q("S1-20", "short summary of the investigative world chapter", "normal", ["science", "investigat"], want_science=True),
    ]),
    chapter("science_ch3_health", "Science", 37, "Chapter 3 - Health: The Ultimate Treasure", [
        Q("S3-01", "why do they call health the ultimate treasure?", "normal", ["health"], want_science=True),
        Q("S3-02", "what things keep us healthy according to the chapter?", "normal", ["health"], want_science=True),
        Q("S3-03", "how does disease spread? explain like steps", "interactive", ["disease", "health", "spread"], want_science=True),
        Q("S3-04", "why should i wash my hands?", "normal", ["hand", "wash", "hygiene", "germ"], want_science=True),
        Q("S3-05", "what is hygiene in simple words?", "normal", ["hygiene", "health"], want_science=True),
        Q("S3-06", "show a figure about health or disease from the book", "diagram", ["figure", "health", "image"], want_images=True, want_science=True),
        Q("S3-07", "what foods help us stay healthy?", "normal", ["food", "health"], want_science=True),
        Q("S3-08", "quiz me on health with one easy question", "normal", ["health", "?"], want_science=True),
        Q("S3-09", "what is immunity roughly?", "normal", ["immun", "health", "body"], want_science=True),
        Q("S3-10", "difference between healthy and disease-free life?", "normal", ["health", "disease"], want_science=True),
        Q("S3-11", "how does exercise help?", "normal", ["exercise", "health"], want_science=True),
        Q("S3-12", "why sleep matters for health", "normal", ["sleep", "health"], want_science=True),
        Q("S3-13", "can stress affect health in this chapter?", "normal", ["health", "stress", "mental", "emotion"], want_science=True),
        Q("S3-14", "prevention vs cure — what does the chapter say?", "normal", ["prevent", "health", "disease"], want_science=True),
        Q("S3-15", "give 3 healthy habits from the chapter", "normal", ["health", "habit"], want_science=True),
        Q("S3-16", "what is hygene and why it matter?", "typo", ["hygiene", "health"], want_science=True),
        Q("S3-17", "did marathas invent vaccines in this health chapter?", "wrong", ["health", "not"], ["maratha"]),
        Q("S3-18", "is health only about medicines?", "wrong", ["health", "habit", "food", "not"], want_science=True),
        Q("S3-19", "explain how germs enter the body simply", "interactive", ["germ", "body", "disease"], want_science=True),
        Q("S3-20", "why is helth called ultimat tresure?", "typo", ["health"], want_science=True),
    ]),
    chapter("social_ch1_natural_resources", "Social", 32, "Chapter 1 - Natural Resources and Their Use", [
        Q("So1-01", "what are natural resources? give easy examples", "normal", ["resource", "natural"]),
        Q("So1-02", "why should we use them carefully?", "normal", ["resource", "care", "sustain"]),
        Q("So1-03", "difference between renewable and non-renewable?", "normal", ["renewable", "resource"]),
        Q("So1-04", "show me a map or picture about natural resources from the book", "diagram", ["resource", "map", "figure", "image"], want_images=True),
        Q("So1-05", "what is water as a resource?", "normal", ["water", "resource"]),
        Q("So1-06", "what about forests and wildlife?", "normal", ["forest", "resource", "wildlife"]),
        Q("So1-07", "how do humans overuse resources?", "normal", ["resource", "use", "over"]),
        Q("So1-08", "quiz me one question on natural resources", "normal", ["resource", "?"]),
        Q("So1-09", "what is conservation in this chapter?", "normal", ["conserv", "resource"]),
        Q("So1-10", "examples of minerals as resources", "normal", ["mineral", "resource"]),
        Q("So1-11", "why is soil important?", "normal", ["soil", "resource"]),
        Q("So1-12", "can air be a natural resource?", "normal", ["air", "resource"]),
        Q("So1-13", "what happens if we waste resources?", "normal", ["resource", "waste"]),
        Q("So1-14", "how can students help save resources?", "normal", ["resource", "save", "student"]),
        Q("So1-15", "give 4 bullets of key points", "normal", ["resource"]),
        Q("So1-16", "what are naturall resorces used for?", "typo", ["resource", "natural"]),
        Q("So1-17", "did shivaji discover coal in this chapter?", "wrong", ["resource", "not"], ["shivaji"]),
        Q("So1-18", "is this chapter only about mughal maps?", "wrong", ["resource", "natural", "not"], ["mughal"]),
        Q("So1-19", "i mixed renewable — explain again slowly", "normal", ["renewable", "resource"]),
        Q("So1-20", "what is conservasion of resorces?", "typo", ["conserv", "resource"]),
    ]),
    chapter("social_ch2_political_map", "Social", 33, "Chapter 2 - Reshaping India’s Political Map", [
        Q("So2-01", "what is a political map anyway?", "normal", ["political", "map"]),
        Q("So2-02", "how is it different from a physical map?", "normal", ["political", "physical", "map"]),
        Q("So2-03", "who were the mughals in this chapter?", "normal", ["mughal"]),
        Q("So2-04", "can you show the political map figure?", "diagram", ["map", "figure", "political"], want_images=True),
        Q("So2-05", "how did india's political map get reshaped?", "normal", ["map", "political", "india"]),
        Q("So2-06", "what kingdoms or powers are discussed?", "normal", ["kingdom", "mughal", "power", "empire"]),
        Q("So2-07", "why do maps change over time?", "normal", ["map", "change"]),
        Q("So2-08", "quiz me on political map with one question", "normal", ["map", "political", "?"]),
        Q("So2-09", "what is an empire in this context?", "normal", ["empire", "mughal"]),
        Q("So2-10", "any famous rulers named here?", "normal", ["ruler", "mughal", "akbar", "aurangzeb", "babur"]),
        Q("So2-11", "what regions changed hands?", "normal", ["region", "map", "territory"]),
        Q("So2-12", "why is this chapter called reshaping?", "normal", ["reshap", "map"]),
        Q("So2-13", "how do historians use maps?", "normal", ["map", "histor"]),
        Q("So2-14", "give two important takeaways", "normal", ["map", "political"]),
        Q("So2-15", "explain like im new to history maps", "normal", ["map", "political"]),
        Q("So2-16", "what is politcal map of india in this chaptre?", "typo", ["political", "map"]),
        Q("So2-17", "did mughals invent the steam engine here?", "wrong", ["mughal", "map", "not"], ["steam"]),
        Q("So2-18", "is this chapter about perfect squares?", "wrong", ["map", "political", "not"], ["square"]),
        Q("So2-19", "show another map related image if you can", "diagram", ["map", "figure", "image"], want_images=True),
        Q("So2-20", "who were the mughuls on the map?", "typo", ["mughal", "map"]),
    ]),
    chapter("social_ch3_marathas", "Social", 34, "Chapter 3 - The Rise of the Marathas", [
        Q("So3-01", "who was shivaji and why are the marathas important?", "normal", ["shivaji", "maratha"]),
        Q("So3-02", "how did the marathas rise?", "normal", ["maratha", "rise"]),
        Q("So3-03", "where did maratha power grow geographically?", "normal", ["maratha", "maharashtra", "deccan", "region"]),
        Q("So3-04", "show a map or figure about marathas if available", "diagram", ["maratha", "map", "figure"], want_images=True),
        Q("So3-05", "what strategies did shivaji use?", "normal", ["shivaji", "guerrilla", "fort", "strategy"]),
        Q("So3-06", "who opposed the marathas?", "normal", ["mughal", "maratha", "oppose"]),
        Q("So3-07", "quiz me one easy maratha question", "normal", ["maratha", "shivaji", "?"]),
        Q("So3-08", "what is a fort's role in maratha history?", "normal", ["fort", "maratha", "shivaji"]),
        Q("So3-09", "why is this rise important for india's history?", "normal", ["maratha", "history"]),
        Q("So3-10", "any other leaders after shivaji mentioned?", "normal", ["maratha", "peshwa", "leader"]),
        Q("So3-11", "explain guerilla warfare simply", "normal", ["guerrilla", "guerilla", "hit", "war", "shivaji"]),
        Q("So3-12", "how did administration or revenue work roughly?", "normal", ["admin", "revenue", "maratha", "tax"]),
        Q("So3-13", "give 3 key points on rise of marathas", "normal", ["maratha"]),
        Q("So3-14", "what challenges did they face?", "normal", ["maratha", "challenge", "mughal"]),
        Q("So3-15", "compare marathas briefly with mughals if chapter does", "normal", ["maratha", "mughal"]),
        Q("So3-16", "who was shivaji and the marathas risee?", "typo", ["shivaji", "maratha"]),
        Q("So3-17", "did the marathas invent the steam engine in this chapter?", "wrong", ["maratha"], ["steam"]),
        Q("So3-18", "is this chapter about perfect cubes in math?", "wrong", ["maratha", "not"], ["cube"]),
        Q("So3-19", "tell me one more thing about how the marathas rose", "normal", ["maratha", "rise"]),
        Q("So3-20", "who was shivajii again briefly?", "typo", ["shivaji", "maratha"]),
    ]),
]


def main():
    BANKS.mkdir(parents=True, exist_ok=True)
    for ch in CHAPTERS:
        (BANKS / f"{ch['slug']}.json").write_text(json.dumps(ch, indent=2))
        print("wrote", ch["slug"])
    (BANKS / "_index.json").write_text(
        json.dumps(
            [{"slug": c["slug"], "subject": c["subject"], "chapter_id": c["chapter_id"], "chapter": c["chapter"]} for c in CHAPTERS],
            indent=2,
        )
    )
    print("total", len(CHAPTERS))


if __name__ == "__main__":
    main()
